package com.example.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.greendao.NewsContent;

import com.example.greendao.NewsContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsContentDaoConfig;

    private final NewsContentDao newsContentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsContentDaoConfig = daoConfigMap.get(NewsContentDao.class).clone();
        newsContentDaoConfig.initIdentityScope(type);

        newsContentDao = new NewsContentDao(newsContentDaoConfig, this);

        registerDao(NewsContent.class, newsContentDao);
    }
    
    public void clear() {
        newsContentDaoConfig.getIdentityScope().clear();
    }

    public NewsContentDao getNewsContentDao() {
        return newsContentDao;
    }

}
