package com.example.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NEWS_CONTENT".
 */
public class NewsContent {

    private Long id;
    private String newsId;
    private String content;

    public NewsContent() {
    }

    public NewsContent(Long id) {
        this.id = id;
    }

    public NewsContent(Long id, String newsId, String content) {
        this.id = id;
        this.newsId = newsId;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNewsId() {
        return newsId;
    }

    public void setNewsId(String newsId) {
        this.newsId = newsId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
